### ISSUE TITLE
javascript_showcase.fmp12 Login/Password Missing

### ISSUE THREAD

**Issue by glitchtracker** [beezwax/FMAjax#1]
Hi,
I was curious about the javascript_showcase.fmp12 file, but unfortunately I can't open it as it's password protected. I tried the usual Admin / Blank but its doesn't work.
Could you provide an unlocked version ?

**Comment by rainbat** [comment]
@glitchtracker 
hi, just ran across the same issue:
login is:
admin / admin

... but you probably already found out 😎

**Comment by ryanlsimms** [comment]
I've removed the password on the latest.  Admin username is "admin" in case there's any doubt.
